### ISSUE TITLE
Remove everything that's not AsyncSeq

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Control.AsyncSeq#1]

**Comment by CarstenKoenig** [comment]
I will have a look at this later today - want it in a dev branch for now?

**Comment by forki** [comment]
I already have a commit here hich removes most stuff, but can't push because of  DDOS of github...

**Comment by forki** [comment]
* the stuff that can't be removed should be internalized.
* try to get everything into one file so that we can use paket to link the file

**Comment by dsyme** [comment]
@CarstenKoenig  - I jumped in and did most of this in #4, please take a look, thanks

**Comment by CarstenKoenig** [comment]
yes this should fix both - thank you.

As we are at it - what workflow do you prefer here: fork the repo and bring in pull-requests? Working on branches and merging those? Who is the one responsible for the main branch and/or release branches?

Sorry if there is a document somewhere explaining all this - just point me to it please ;)

Thanks

**Comment by forki** [comment]
in many other ProjectScaffold like projects we release basically everthing that's merged to master. The process is described at http://fsprojects.github.io/ProjectScaffold/release-process.html - but someone has to maintain the release-notes file and decide the version

**Comment by dsyme** [comment]
Fork + pull requests.  In this case I self-committed to get us to the right baseline quickly

**Comment by CarstenKoenig** [comment]
ok - thanks - cleaning up the tangling branch then

**Comment by dsyme** [comment]
I think anyone with admin rights to both this repo and the nuget package can push releases of packages + docs ("build Release")

**Comment by forki** [comment]
This is a good point. you should allow more people to push to https://www.nuget.org/packages/FSharp.Control.AsyncSeq ;-)
