### ISSUE TITLE
nuget publish

### ISSUE THREAD

**Issue by wilsoncg** [fsprojects/FSharp.Control.AsyncSeq#104]
@eulerfx / @dsyme 
How to bump the nuget package version?
I'd also like to re-publish the API documentation at the same time (as now the links to line numbers in master are out of whack because of commits).

**Comment by dsyme** [comment]
Hi @wilsoncg, my apologies for the delay.

Bumping the version number is simply adding a new entry to `https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/master/RELEASE_NOTES.md`

thanks
don
