### ISSUE TITLE
GitHub link in documentation points to wrong line number

### ISSUE THREAD

**Issue by akeeton** [fsprojects/FSharp.Control.AsyncSeq#105]
### Description

In the [documentation for `map`][1], the link to the GitHub source is incorrect.  It points to [line 950][2]. Instead, it should point to [line 956][3].

### Repro steps

Please provide the steps required to reproduce the problem

1. Visit https://fsprojects.github.io/FSharp.Control.AsyncSeq/reference/fsharp-control-asyncseq.html
2. Scroll down to the documentation for `map`
3. Click on the link to the GitHub source code

### Expected behavior

The link should have a line anchor to `map` in the source code

### Actual behavior

The link has a line anchor to a few lines above `map`

### Known workarounds

N/A

### Related information 

N/A

  [1]: https://fsprojects.github.io/FSharp.Control.AsyncSeq/reference/fsharp-control-asyncseq.html
  [2]: https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/master/src/FSharp.Control.AsyncSeq/AsyncSeq.fs#L950-950
  [3]: https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/master/src/FSharp.Control.AsyncSeq/AsyncSeq.fs#L956

**Comment by wilsoncg** [comment]
Let me see if I can fix up

**Comment by wilsoncg** [comment]
Ok, making progress. Documentation has been updated and pushed to gh-pages branch, so github links look correct, can you verify you are happy?

**Comment by akeeton** [comment]
Looks good.
