### ISSUE TITLE
Can't find v2.0.22 on NuGet

### ISSUE THREAD

**Issue by hotyes** [fsprojects/FSharp.Control.AsyncSeq#106]
Hi there, just realised that can't find version 2.0.22 on nuget but based on the RELEASE_NOTES its already released

https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/master/RELEASE_NOTES.md#2022---28052019

**Comment by wilsoncg** [comment]
Apologies, I was having issues with the nuget publish last time I tried. 
I have now published 2.0.22.
Now help documentation & release notes & assembly info should all line up.
Let me know if looks good for you too?

**Comment by hotyes** [comment]
thanks !
