### ISSUE TITLE
Can a new release with asyncseq support be published?

### ISSUE THREAD

**Issue by baronfel** [fsprojects/FSharp.Control.AsyncSeq#109]
### Description

With the release of .net core 3.0 and C# 8, AsyncEnumerables are becoming more prevalent. The AsyncSeq support for them has not yet been released and I see questions about it fairly-often on the FSSF slack.  Could a new version of this library be published with those additions?

**Comment by fluxlife** [comment]
Bump

**Comment by wilsoncg** [comment]
bear with me, let me attempt a release

**Comment by wilsoncg** [comment]
That's it released.
Note, API generated reference docs does not currently contain the new ofAsyncEnum/toAsyncEnum because generation target points at net 45 (Framework) output, which does not contain added IAsyncEnumerable method.
I will see what is possible for adding into the documentation.
