### ISSUE TITLE
AsyncSeq.scan behaves differently from Seq.scan (doesn't emit initial state)

### ISSUE THREAD

**Issue by eulerfx** [fsprojects/FSharp.Control.AsyncSeq#11]
Not sure if it should, but issue shown in:
https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/e092247f4596567a9255669ad74680b52e0caf28/tests/FSharp.Control.AsyncSeq.Tests/AsyncSeqTests.fs#L152

**Comment by dsyme** [comment]
Agreed these should be consistent. Can someone take this and submit a PR?

**Comment by eulerfx** [comment]
I'll do it.

**Comment by eulerfx** [comment]
Fixed with https://github.com/fsprojects/FSharp.Control.AsyncSeq/commit/8c6cebe52b59d00b4f87b31c6e47db1b32963a0e
