### ISSUE TITLE
Fable support?

### ISSUE THREAD

**Issue by njlr** [fsprojects/FSharp.Control.AsyncSeq#110]
As it stands now, it this library does not seem to support Fable. According to [the Fable docs](https://fable.io/docs/your-fable-project/author-a-fable-library.html), it is quite simple to add by modifying the project file:

```xml
<!-- Add source files to "fable" folder in Nuget package -->
<ItemGroup>
    <Content Include="*.fsproj; **\*.fs" PackagePath="fable\" />
</ItemGroup>
```

Is Fable support something that would be accepted in a PR?

**Comment by dsyme** [comment]
> Is Fable support something that would be accepted in a PR?


Yes

**Comment by Shmew** [comment]
I just spent some time on this to see if it's reasonably possible, which it doesn't appear to be unfortunately. You can see all of the code that has to be blocked out in this [commit](https://github.com/Shmew/FSharp.Control.AsyncSeq/commit/90067caaa11f502a9c5694079b9f603941f75680).

**Comment by dsyme** [comment]
Hmmm it's not a huge change, 26 lines in this file https://github.com/Shmew/FSharp.Control.AsyncSeq/commit/90067caaa11f502a9c5694079b9f603941f75680#diff-f33750e1be3b0c8a2b10b87e5036e825

**Comment by Shmew** [comment]
Yeah, I was still getting a lot of compiler errors with that. I'm not really sure just how much of the functionality is stripped with those changes. I haven't used this library before, but I re-discovered it and was hoping to use it on both the front-end and back-end for SignalR streaming.

**Comment by Shmew** [comment]
After some more tinkering:

![image](https://user-images.githubusercontent.com/11186595/84668343-26cfff80-aee9-11ea-9c83-eb36d8c691f9.png)

**Comment by Shmew** [comment]
I think I've got all the kinks worked out, there was some things I had to adjust with compiler directives to get them to work with Fable, but it seems to be going smoothly now. Should be able to put in a PR in the next couple days after I work my way through all these tests.

![image](https://user-images.githubusercontent.com/11186595/84729812-3cc9d880-af5a-11ea-9083-9ed3cf1730b1.png)

**Comment by wilsoncg** [comment]
@Shmew good work, let me know when ready and I can help with a release.

**Comment by Shmew** [comment]
So I haven't looked into this yet since I'm just getting the main things working that should work ootb, but how open are you all to me implementing alternative fable-friendly versions of the pieces of this that use tasks (since tasks aren't supported by Fable) toggled with compiler directives? 

As it stands, these will not be supported:
* iterAsyncParallel
* iterAsyncParallelThrottled
* ofObservableBuffered
* toBlockingSeq
* cache
* combineLatestWithAsync
* combineLatestWith
* combineLatest
* takeUntilSignal
* skipUntilSignal
* bufferByCountAndTime
* bufferByTime
* mergeChoice
* merge
* mergeAll
* mapAsyncParallel
* groupByAsync
* groupBy
* Seq.ofAsyncSeq
* AsyncSeqSrc<'T>

**Comment by dsyme** [comment]
> So I haven't looked into this yet since I'm just getting the main things working that should work ootb (should be finished with this in the next hour or so), but how open are you all to me implementing alternative fable-friendly versions of the pieces of this that use tasks (since tasks aren't supported by Fable) toggled with compiler directives?

I think it's ok, but in a separate PR so we can assess the complexification.

**Comment by Shmew** [comment]
I fixed a few things that were necessary to get the bulk of things working (functions that don't use tasks under the hood). I'm not really sure I can fix the other things without a `Fable.Core` dependency to replace the usage of tasks... so I think the PR is as good as it gets with that being said.
