### ISSUE TITLE
Best way to convert System.Collections.Generic.IAsyncEnumerable<'t> to AsyncSeq<'t>?

### ISSUE THREAD

**Issue by fwaris** [fsprojects/FSharp.Control.AsyncSeq#119]
The Azure EventHub API returns a IAsyncEnumberable<'t> (from BCL).

I would like to convert it to asyncSeq (or FSharp.Control.IAsyncEnumerable<'t>) (for obvious reasons). 

The following code type checks but there might be a better way that I am missing. Any suggestions would be appreciated.

```F#
    let toAsyncSeq<'t> (xs:System.Collections.Generic.IAsyncEnumerable<'t>) =
        let aeEnum = xs.GetAsyncEnumerator()
        let rec loop() = 
            asyncSeq {
                let! haveData = aeEnum.MoveNextAsync().AsTask() |> Async.AwaitTask
                if haveData then 
                    yield aeEnum.Current
                    yield! loop()
            }
        loop()
```

**Comment by fwaris** [comment]
This works (the first version does not as it unallocates aeEnum). This also properly handles disposition.

```F#
    let toAsyncSeq<'t> (xs:System.Collections.Generic.IAsyncEnumerable<'t>) =
        {new IAsyncEnumerable<'t> with
            member _.GetEnumerator() =        
                let aeEnum = xs.GetAsyncEnumerator()
                {
                    new IAsyncEnumerator<'t> with 
                        member _.MoveNext() = 
                            async {
                                let! haveData = aeEnum.MoveNextAsync().AsTask() |> Async.AwaitTask
                                if haveData then return Some aeEnum.Current else return None
                            }

                    interface IDisposable with
                        member IDisposable.Dispose() = 
                            async {
                                do! aeEnum.DisposeAsync().AsTask() |> Async.AwaitTask
                            }
                            |> Async.RunSynchronously
                }
        }

```

**Comment by fwaris** [comment]
I did not realize this before but the .net core version of AsyncSeq does have a function 'AsyncSeq.ofAsyncEnum' to convert from BCL IAsyncEnumberable<'t> to the FSharp.Control.IAsyncEnumberable<'t>. 

The .net framework version of the package does not. I was using the .net framework version earlier as I also wanted to use fsharp interactive with EventHubs and therefore had to write my own conversion. FSI is based on .net framework in VS 2019 at least as of now.

**Comment by wilsoncg** [comment]
@fwaris 
> FSI is based on .net framework in VS 2019

Yes this one has caught me out a few times now. A lot of F# developers in the community are using vscode as their preferred environment, development on the tooling seems to iterate just a tad quicker. 

Also, you could try `dotnet fsi` with .NET 5.0 installed, that should give you .NET core?

**Comment by fwaris** [comment]
@wilsoncg I also use vscode but intellisense does not work well for .fsx files in vscode.

Intellisense works fine for files inside a project.

Also I am now using [#r "nuget: ...."](https://devblogs.microsoft.com/dotnet/announcing-f-5/) refs in .fsx files and I don't see them working in vscode even with the 'languagepreview' flag set.

**Comment by wilsoncg** [comment]
@fwaris Ok, I've just tried out and it works in vscode with ionide 4.17.0.

- .NET 5.0 installed, vscode with ionide 4.17.0
- there is no global.json on the directory path which overrides the sdk version chosen
- create new F# console fsproj `dotnet new console --language F#`
- add .fsx file to fsproj
- in settings.json set `"FSharp.fsiExtraParameters": ["--langversion:preview"]`
- vscode reload window (possibly relaunch vscode) after updating settings.json

You should now see syntax highlighting play nicely with `#r nuget` syntax, using ionide & FSAC. 

There is a new build of [ionide 5.0.0](https://github.com/ionide/ionide-vscode-fsharp/releases/tag/5.0.0-preview02) coming very soon, which will use .NET 5.0 by default & should mean `--langversion` is not needed.

![image](https://user-images.githubusercontent.com/1066103/100486177-d1845500-30fa-11eb-9ecc-ab8192c1be4a.png)

**Comment by fwaris** [comment]
@wilsoncg appreciate your help. Indeed the above works however adding a moderate amount of complexity to the script stops intellisense from working in vscode - please see below:

```F#
let torchlib = @"C:\Users\Admin\.nuget\packages\libtorch-cpu\1.7.0.1\runtimes\win-x64\native\torch_cpu.dll"
let _ = System.Runtime.InteropServices.NativeLibrary.Load torchlib

#r "nuget: DiffSharp-cpu,1.0.0-preview-387146713"
#r "nuget:XPlot.Plotly"
open XPlot.Plotly

let stacks = {|
    Name = "Name"
    Hours = [23;22;12]
|}
open DiffSharp
```
The code works fine when submitted to fsi so it is correct code (Note: you will have to set the correct path to the referenced native library, for your own environment)
