### ISSUE TITLE
Support .NET Standard 2.0

### ISSUE THREAD

**Issue by bddckr** [fsprojects/FSharp.Control.AsyncSeq#124]
Is there a reason this awesome project is targeting .NET Standard 2.1 instead of 2.0? It seems to work just fine for me after I changed this line:
https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/0ebf3426138aa2e1b796c28a50a87efef07ce405/src/FSharp.Control.AsyncSeq/AsyncSeq.fs#L1749

In one of my projects I'm targeting .NET Framework, which ends with [support for .NET Standard 2.0](https://docs.microsoft.com/dotnet/standard/net-standard#net-implementation-support).

**Comment by wilsoncg** [comment]
I think the idea was to simplify the maintenance process. The build process was getting a bit hairy, unit tests & document generation were running as .NET framework (thanks to a dependency on Razor formatting), whilst build & package ran in .NET core. Throw into the mix a separate CI build for mono and suddenly maintenance becomes quite the headache. 

Now that .NET framework's days are numbered, it seems sensible to baseline on .NET Standard 2.1 to simplify cross platform development & maintenance. You can use versions <3.0 if you want .NET framework support.

**Comment by bddckr** [comment]
That all makes sense to me. Thanks for the insight!

**Comment by toburger** [comment]
As your library is used as a transient dependency from other libraries the use of `netstandard2.1` imposes some problems.

If the library itself is built with `netstandard2.0` the following warning get's shown:
> warning NU1608: Detected package version outside of dependency constraint: FSharp.Azure.Storage 5.0.1 requires FSharp.Control.AsyncSeq (>= 2.0.0 && < 3.0.0) but version FSharp.Control.AsyncSeq 3.0.3 was resolved.

The lib should run with `netstandard2.0` perfectly fine. No need to support old .NET Framework?

**Comment by dsyme** [comment]
I'm fine with adding netstandard2.0 tbh, and trimming out the other functionality

**Comment by bddckr** [comment]
Thanks for the work in #135! ❤️

Can we get this released to NuGet.org? I think we can close this issue once it's out 😄

**Comment by dsyme** [comment]
3.0.5 released with support for both netstandard2.0 and netstandard2.1 https://www.nuget.org/packages/FSharp.Control.AsyncSeq/3.0.5
