### ISSUE TITLE
[Feature] Can we have sort, sortBy, sortDescending and sortByDescending methods for AsyncSeq?

### ISSUE THREAD

**Issue by voroninp** [fsprojects/FSharp.Control.AsyncSeq#126]
It would be nice to have as many counterpart methods of `Seq` as possible. `AsyncEnumerable` extensions in `System.Interactive.Async` package contains these extensions for `IAsyncEnumerable`.

**Comment by dsyme** [comment]
Yes, agreed - would you like to submit a PR? :-)

**Comment by voroninp** [comment]
Ok, I'll try to do it ;-)

**Comment by dsyme** [comment]
Done! thanks!
