### ISSUE TITLE
netstandard2.1 only target forbids using the library in .net framework

### ISSUE THREAD

**Issue by smoothdeveloper** [fsprojects/FSharp.Control.AsyncSeq#132]
It seems since v3 release, this library is only targetting netstandard2.1.

It is not possible to reference it in F# projects targetting .net framework.

Can we add a separate target for it or set it back to netstandard2.0?

**Comment by bddckr** [comment]
See #124.

I've been using the latest [`AsyncSeq.fs`](https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/master/src/FSharp.Control.AsyncSeq/AsyncSeq.fs) and just adjusted the `#ifdef`s to allow netstandard2.0 without issues so far.

**Comment by dsyme** [comment]
Close in favour of https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/124

**Comment by dsyme** [comment]
3.0.5 released with support for both netstandard2.0 and netstandard2.1 https://www.nuget.org/packages/FSharp.Control.AsyncSeq/3.0.5
