### ISSUE TITLE
Resources, AsyncSeq, Try Finally and possible alternative definitions

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Control.AsyncSeq#15]
In general we expect sensible behaviour for sub-sequences of AsyncSeq objects (those returned by tail, skip etc.) 

When I look at the definition of something like ``ofObservableUsingAgent `` I see an AsyncSeq which has internal resources - an agent - and, if you replayed the_tail_ of the sequence multiple times, or if you didn't iterate all the way through the sequence, then you'd get some odd behaviour - each time you're replying it you're communicating with the agent and presumably getting different replies. The agent allocated at the start represents shared state, shared between all the various sub-sequences returned. Also, the agent only gets collected if the sequence gets iterated all the way to the end.

  let internal ofObservableUsingAgent (input : System.IObservable<_>) f = 
    asyncSeq {  
      use agent = AutoCancelAgent.Start(f)
      ...
      yield! loop() }

All this stems from the fact that the definition of AsyncSeq is currently much like a lazy list, just asynchronous (indeed it's name could almost be AsyncList).  The "tail" operation drops the head, and a "cons" would put a different head on etc.  Attempts to use shared mutable resources in LazyList-like combinators usually results them being shared in all "tail" instances, with odd results.  

Basically, LazyList-like structures can't hold shared-mutable or disposable resources during iteration.  That's one advantage of ``IEnumerable<'T>`` over ``LazyList<'T>``, because IEnumerable separates iteration from data, and iterators can hold state.

To give another example, the current "algebraic" definition is problematic w.r.t. the behaviour of  "use" .  As things stand today, when you use "use" in an ``asyncSeq { ... }`` 

(a) The compensation functions are only executed if the consuming iteration completes to the _end_ of the sequence - and not if an early exit occurs.  (In contrast, IEnumerator objects can be disposed at any point during the iteration.)

(b) The compensation functions will be executed every time the "tail" of an async seq is iterated to its end.  (In contrast, a separate IEnumerator object is created for each iteration.)

Basically, it's probably not a good idea to try have both an algebraic definition of AsyncSeq _and_ support using/try-finally.

All these problems leads to the possible alternative definition of AsyncSeq as an async version of iterators:

      type IAsyncEnumerator<'T> = 
          abstract MoveNext : Async<bool>
          abstract Current : 'T
          abstract Dispose : unit -> unit  (* or Async<unit> *)

      type IAsyncEnumerable<'T> = 
          abstract GetEnumerator : unit -> IAsyncEnumerator<'T>

      type AsyncSeq<'T> = IAsyncEnumerable<'T>

I actually think we need to do a comparison between the current "algebraic" definition of AsyncSeq and alternative "iterator" definitions. The iterator definition is in many ways the "natural" definition of asynchronous sequences for F#, at least if you take "sequence" = "iterable".  

In particular, the "iterator" definition allows a sensible notion of "Dispose" on the iterators, which allows them to have resource - very similarly to the case above.

Note that APIs can often have problems like this without them being observed as a significant problem in practice because in most cases AsyncSeq objects are one-shot - they are only ever iterated once, or iterations of the outermost object are independent as for Seq.  

Cheers
Don

**Comment by dsyme** [comment]
To be concrete, given the following:

    #r "../../../bin/FSharp.Control.AsyncSeq.dll"
    open FSharp.Control

    let printer() = printfn "allocate"; { new System.IDisposable with member __.Dispose() = printfn "disposed" }
    let a = 
        asyncSeq { use _d = printer()
                   yield 1
                   yield 2 }

Then this prints "allocate" (without deallocate):

    a |> AsyncSeq.take 1  |> AsyncSeq.iter(fun _ -> ()) |> Async.RunSynchronously

likewise this (which surprised me even more)

    a |> AsyncSeq.take 2  |> AsyncSeq.iter(fun _ -> ()) |> Async.RunSynchronously

You only get a deallocate like this:

    a |> AsyncSeq.take 3  |> AsyncSeq.iter(fun _ -> ()) |> Async.RunSynchronously

**Comment by eulerfx** [comment]
A type that can help address resource management is as follows (from [issue](https://github.com/fsprojects/FSharpx.Async/issues/19)  and [source code](https://github.com/eulerfx/FSharpx.Async/blob/asyncpipe/src/FSharpx.Async/AsyncPipe.fs)):

```fsharp
/// An async pipeline which consumes values of type 'i, produces
/// values of type 'o and completes with a result 'a or an error.
type AsyncPipe<'i, 'o, 'a> = Async<AsyncPipeStep<'i, 'o, 'a>>

/// An individual step in an async pipeline.
and AsyncPipeStep<'i, 'o, 'a> =

  /// The pipeline completed with result 'a.
  | Done of 'a

  /// The pipeline is emitting a value of type 'o.
  | Emit of 'o * AsyncPipe<'i, 'o, 'a>

  /// The pipeline is consuming a value of type 'i.
  | Await of ('i option -> AsyncPipe<'i, 'o, 'a>)
```

This is more generic than required by `AsyncSeq` alone, but one of the things it can ensure is deterministic resource disposal. The idea would be to have the iterator be an async pipe which awaits input, and the async sequence be an async pipe which emits outputs. Then iteration is a [fusion](https://github.com/eulerfx/FSharpx.Async/blob/asyncpipe/src/FSharpx.Async/AsyncPipe.fs#L157) of these two pipes. In particular, fusion can ensure that an emitting pipe is drained. I'll come up with a sample over the weekend...

**Comment by eulerfx** [comment]
One way to adapt this more directly to `AsyncSeq` is to add an explicit compensation function:

```fsharp
type AsyncSeq<'T> = Async<AsyncSeqInner<'T> * (unit -> unit)> 

and AsyncSeqInner<'T> = 
  | Nil
  | Cons of 'T * AsyncSeq<'T>
  

type Async with
  static member map f a = async.Bind(a, f >> async.Return)
  static member bind f a = async.Bind(a, f)


let empty<'T> : AsyncSeq<'T> = async.Return(Nil,id)

let singleton (item:'T) : AsyncSeq<'T> =
  async.Return(Cons(item,empty),id)

let rec tryFinally (s:AsyncSeq<'T>) (comp:unit -> unit) : AsyncSeq<'T> = async {
  try
    let! s = s
    match s with
    | Nil,comp' -> return Nil,(comp' >> comp)
    | Cons(a,tl),comp' -> return Cons(a,tryFinally tl comp),(comp' >> comp)
  with ex ->
    comp()
    return raise ex }

let rec append (f:AsyncSeq<'T>) (s:AsyncSeq<'T>) : AsyncSeq<'T> =
  f |> Async.bind (function
    | Nil,comp -> tryFinally s comp
    | Cons(a,tl),comp -> (Cons(a, append tl s),comp) |> async.Return)

let rec collect (f:'T -> AsyncSeq<'U>) (s:AsyncSeq<'T>) : AsyncSeq<'U> =
  s |> Async.bind (function
    | Nil,comp -> (Nil,comp) |> async.Return
    | Cons(a,tl),comp -> async { 
      return! append (f a) (collect f tl)
    })

let rec iterAsync (f:'T -> Async<unit>) (s:AsyncSeq<'T>) : Async<unit> =
  s |> Async.bind (function
    | Nil,comp -> async { comp() }
    | Cons(a,tl),comp -> async {
      try
        do! f a
        return! iterAsync f tl 
      with ex ->
        comp()
        return raise ex
    })

let rec ofList (ls:'T list) : AsyncSeq<'T> =
  match ls with
  | [] -> (Nil,id) |> async.Return
  | hd::tl -> (Cons(hd, ofList tl),id) |> async.Return

let rec take (count:int) (s:AsyncSeq<'T>) : AsyncSeq<'T> =
  s |> Async.map (function
    | Nil,comp -> Nil,comp
    | Cons(a,tl),comp ->
      if count = 0 then Nil,comp
      else Cons(a, take (count - 1) tl),comp)
type AsyncSeqBuilder() =
  member x.Yield(v) = singleton v
  member x.Return(()) = empty
  member x.YieldFrom(s) = s
  member x.Zero () = empty
  member x.Bind (inp:Async<'T>, body : 'T -> AsyncSeq<'U>) : AsyncSeq<'U> = 
    async.Bind(inp, body)
  member x.Combine (seq1:AsyncSeq<'T>,seq2:AsyncSeq<'T>) = 
    append seq1 seq2
  member x.While (gd, seq:AsyncSeq<'T>) = 
    if gd() then x.Combine(seq,x.Delay(fun () -> x.While (gd, seq))) else x.Zero()
  member x.Delay (f:unit -> AsyncSeq<'T>) = 
    async.Delay(f)
  member x.Using (resource:#IDisposable, binder) = 
    tryFinally (binder resource) (fun () -> 
      if box resource <> null then resource.Dispose())
  member x.TryFinally (body: AsyncSeq<'T>, compensation) = 
    tryFinally body compensation   

let asyncSeq = new AsyncSeqBuilder()

let printer() = printfn "allocate"; { new System.IDisposable with member __.Dispose() = printfn "disposed" }
let a = 
    asyncSeq { use _d = printer()
               yield 1
               yield 2 }

a |> take 1 |> iterAsync (fun _ -> async.Return()) |> Async.RunSynchronously
```

which prints:

```
allocate
disposed
```

**Comment by eulerfx** [comment]
Although it seems the compensation needs to be on the outside of the `Async`, otherwise there is not way to run the compensation if the `Async` call fails.

**Comment by VesaKarvonen** [comment]
Yeah... I've spent quite some time thinking about these issues.

In choice streams the streams are memoized for good reasons using [lazy promises](http://hopac.github.io/Hopac/Hopac.html#def:type%20Hopac.Stream.Stream).  I want choice streams to be consistent so that all consumers of a choice stream get the same sequence of results.  I also don't want any operations embedded in choice streams to be repeated or cancelled each time a consumer requests an element or nondeterministically chooses to consume element from some other stream.

[Choice stream builders](http://hopac.github.io/Hopac/Hopac.html#dec:type%20Hopac.Stream.Builder) do not provide a `use` construct, because such functionality cannot be provided meaningfully given the semantics of choice streams.  There is support for [finalizers](http://hopac.github.io/Hopac/Hopac.html#def:val%20Hopac.Stream.doFinalizeJob), but finalizers can't be used for deterministic resource management.  They work fine for some things, however.  I'm using finalizers to lazily remove Observable subscriptions, for example.

Good luck!

**Comment by dsyme** [comment]
FWIW there is an old port of the (ugly) implementation of the "Seq" combinators from FSharp.Core to get an IAsyncEnumerable builder.  This supports "try/finally" correctly. 

    https://github.com/dsyme/FSharpDemoScripts/blob/master/extlib/AsyncSeq-0.1.fsx#L7

My intuition is that we will have to move to IAsyncEnumerable if we are to support try/finally.  At least, I think I'd prefer an approach based on the conversion of known working synchronous Seq code.
