### ISSUE TITLE
Rename Namespace and Project  and Package to FSharp.Control.AsyncSeq

### ISSUE THREAD

**Issue by forki** [fsprojects/FSharp.Control.AsyncSeq#2]

**Comment by CarstenKoenig** [comment]
I think I'll start with this - should be not to hard ;)

**Comment by CarstenKoenig** [comment]
I changed the namespaces everywhere I could find them:

https://github.com/fsprojects/AsyncSeq/commit/cb6f13624287d733b351293eee4d7c26cc158505

For now I put this into the **develop** branch but I don't think there is much to review.

**Comment by CarstenKoenig** [comment]
Ok done (https://github.com/fsprojects/AsyncSeq/commit/afc1c3e31f65d397d7b6c5980a406048097a9cbf) - is this the desired namespace or do you indeed want everthing to sit in `FSharp.Control.AsyncSeq` (including `FSharp.Control.AsyncSeq.AsyncSeq`?)

**Comment by dsyme** [comment]
I edited the title of this issue to "rename project, package and namespace to FSharp.Control.AsyncSeq".  I'd like all three to use the full name, just like FSharp.Compiler.CodeDom, or FSharp.Collections.ParallelSeq.

I'll rename the repo in a bit.

Thanks
don

**Comment by forki** [comment]
Then there is also the nuget package that needs to be renamed

**Comment by dsyme** [comment]
Yep, will do that.  I'm working on renaming all the doc gen etc will submit a PR soon

**Comment by dsyme** [comment]
OK, this is all done now.
