### ISSUE TITLE
Project needs a new logo

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Control.AsyncSeq#28]
This project currently uses the unadorned FSSF Logo for F#.  It really needs a logo of its own more in line with other projects.

Suggestions?

**Comment by tpetricek** [comment]
If it was push-based, I'd vote for:

![](http://www.easyvectors.com/assets/images/vectors/afbig/9abe777790f680d444544d8d78812b36-cannon-clip-art.jpg)

... but since this is pull-async-based, I have no idea!

**Comment by dsyme** [comment]
:)

**Comment by forki** [comment]
Cc @sergey-tihon

**Comment by rhwy** [comment]
![fsharpasyncseq](https://cloud.githubusercontent.com/assets/212965/7908844/40fee8a0-0848-11e5-93a1-8d1fbff72028.png)

should something like that be good enough ?

**Comment by forki** [comment]
wow that's like superman. I wonder if we reverse this for some F# super hero award ;-)

**Comment by forki** [comment]
(read that as I like it very much)

**Comment by rhwy** [comment]
that's because you're a super hero ;-) 
if I PR a svg on this repo that's ok for you?

**Comment by dsyme** [comment]
Works for me :)

**Comment by dsyme** [comment]
closed via #29
