### ISSUE TITLE
Missing XmlTransform library on Linux/Mono

### ISSUE THREAD

**Issue by CarstenKoenig** [fsprojects/FSharp.Control.AsyncSeq#3]
using the `build.sh` script on Linux/Mono you will most likely see this:

```
generate.fsx(27,1): error FS0078: Unable to find the file 'Microsoft.Web.XmlTransform.dll'
```

I think this is the same issue we had here: https://github.com/fsharp/FAKE/issues/587 (or so I think).

Any thoughts on this?

**Comment by MikeBild** [comment]
any workarounds? thx

**Comment by dsyme** [comment]
Since this is just building the docs, the best workaround is to edit build.fsx to skip that step on OSX/Linux.
