### ISSUE TITLE
IAsyncEnumerator<Map<string,int>>' is not a valid enumerator type

### ISSUE THREAD

**Issue by LessIsMore1** [fsprojects/FSharp.Control.AsyncSeq#32]
tables if of type: ``AsyncSeq<Map<string,int>>``

A simple bind
  let x = tables |> AsyncSeq.take 200
gets the following error

The type ``IAsyncEnumerator<Map<string,int>>`` is not a valid enumerator type , i.e. does not have a  'MoveNext()' method returning a bool, and a 'Current' property

**Comment by eulerfx** [comment]
@LessIsMore1 I can't reproduce this, would you provide more code and a description of the environment under which you got the error?
