### ISSUE TITLE
Memory leak when unfolding

### ISSUE THREAD

**Issue by daniel-chambers** [fsprojects/FSharp.Control.AsyncSeq#35]
We're currently trying to use AsyncSeq with an unfold that does repeated HTTP requests that get paged data; each unfold step produces a page of data until we run out of pages, in which case the sequence completes. It looks like AsyncSeq has a memory leak, because we expected that we'd be able to async-enumerate over this sequence consuming and discarding each page of data without constantly increasing memory usage.

Instead, what we've discovered is that AsyncSeq seems to hold onto each page of data in a massive chain of `append` function closures that grows as we enumerate over the async seq. Over time the application's memory usage grows until we finally get an out of memory exception and crash.

Here's a screenshot of a dotMemory profiling session on some similar sample code (below) where I've tracked down the offending chain of objects that's holding everything in memory at once. I've put red boxes around each of the nested `append` closures; the data they hold is of type `TrackingContainer`. You can see each of the TrackingContainer items is a different instance, because I've added a different flag next to each one. This chain continues on further offscreen, further than I was going to follow through the tree view :)

![asyncseqmemoryleak](https://cloud.githubusercontent.com/assets/1214352/10506035/30387824-735f-11e5-888d-2362aab8da9d.png)

The sample code that reproduces this issue (and was used for the above profiling session) is:

```fsharp
open FSharp.Control

type TrackingContainer = TrackingContainer of Data : string list

let generator state =
    async {
        if state < 10000 then
            //In reality this is where we do an HTTP request to get a chunk of data
            //but let's just generate some data inline and wrap it 
            //in a special class we can use to easily identify the chunks of data
            //in a profiler
            return Some (TrackingContainer (Seq.init 100 (fun i -> i.ToString()) |> Seq.toList), state + 1)
        else
            return None
    }
    
let processAsyncSeq (aSeq : _ AsyncSeq) =
    async {
        for TrackingContainer data in aSeq do
            for d in data do
                sprintf "%s" d |> ignore //Busywork with the data
    }

[<EntryPoint>]
let main argv = 
    AsyncSeq.unfoldAsync generator 0
    |> processAsyncSeq
    |> Async.RunSynchronously
    
    0 // return an integer exit code
```

Given the profiling session I did, I _think_ the issue is with `append`, but I'm struggling to fully grok what's going on in the AsyncSeq + Async internals enough to be able to pinpoint exactly _why_ this is happening. :(

**Comment by daniel-chambers** [comment]
I've done a bunch more poking around in the profiler, and I think I've discovered the point where the whole recursively appended sequence of `AsyncSeq`s is being held in memory.

The profiling screenshot above shows outgoing references, so further inward-indented items are data from _later_ in the sequence. Earlier items in the sequence referencing later items seems okay conceptually, but that means that something is holding the earliest item as reference, preventing its GC, even though we've iterated far past it and theoretically don't care about it any more. By holding the earliest around, it holds every single piece in the sequence around too.

So I drilled back up the chain to the very top most AsyncSeq in this nesting and found that it was being held onto by the `iteriAsync` closure.

![rootmostasyncseq](https://cloud.githubusercontent.com/assets/1214352/10513209/cd7b3496-7391-11e5-9d15-e69407cca1f9.png)

When I dig into the decompiled code, I'm pretty sure `_arg1` maps to the reference held on [this line](https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/master/src/FSharp.Control.AsyncSeq/AsyncSeq.fs#L500).

I think the reference to that original source AsyncSeq is being held until after the sequence is fully enumerated is because it's a use binding and the dispose needs to be called after the iteration is complete.

This seems by design, but I doubt the side effect of keeping all the enumerated data in memory is strictly intended, because it makes lazily and asynchronously enumerating through a sequence not usable with large amounts of data and/or a long sequence.

I'm pretty sure it's possible to do tail recursive `seq`s that don't accrue memory like this (please correct me if I'm wrong), and `seq` has the same disposal-chain mechanism that AsyncSeq has. I wonder if any techniques from `seq` could be incorporated here to avoid maintaining the entire chain of `AsyncSeq`s for disposal purposes and bringing along their data with them accidentally?

**Comment by eulerfx** [comment]
I tried running the code using the old "algebraic" version and it doesn't have the issue. I'll take a look.

**Comment by eulerfx** [comment]
The following is sufficient to show the problem:

```fsharp
let generator state =
    async {
        if state < 10000 then
            return Some ((), state + 1)
        else
            return None
    }

AsyncSeq.unfoldAsync generator 0
|> AsyncSeq.iter ignore
|> Async.RunSynchronously
```

**Comment by dsyme** [comment]
It looks like the iterator for an AsyncSeq.append will hold on to the first sequence even after the state machine has moved on to the second sequence.  Specifically the closure of [this object](https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/master/src/FSharp.Control.AsyncSeq/AsyncSeq.fs#L117) will include ``inp1``.  

(That may or may not be the problem, or may be one problem of many :))

**Comment by dsyme** [comment]
#36 fixes the problem

**Comment by dsyme** [comment]
https://www.nuget.org/packages/FSharp.Control.AsyncSeq/

**Comment by daniel-chambers** [comment]
Awesome. Thanks for the fast fix! 

I can confirm that this resolves our large memory leak problem and we're back in action. :)
