### ISSUE TITLE
v2.0.4 on Nuget.org?

### ISSUE THREAD

**Issue by jlewicki** [fsprojects/FSharp.Control.AsyncSeq#44]
I see that there is a 2.0.4 release on GitHub, but 2.0.4 is not listed here: https://www.nuget.org/packages/FSharp.Control.AsyncSeq

I'd like to take advantage of the Profile7 PCL support. Any ETA on when we may see 2.0.4 on nuget?

**Comment by eulerfx** [comment]
Hey @forki or @dsyme I don't seem to have permissions to release. When doing `build Release` I see the following error:

```remote: Permission to fsprojects/FSharp.Control.AsyncSeq.git denied to eulerfx.```

**Comment by dsyme** [comment]
@eulerfx Should now be fixed

**Comment by jlewicki** [comment]
Hello again,

As far as I can tell v2.0.4 still has not been published to nuget? Any chance that could be done soon?

It would be delightful if it was available there so I could reference it from a PCL library.

-John

**Comment by eulerfx** [comment]
@jlewicki apologies for the delay. I did try pushing the package, but not luck even after permissions were updated. Let me give it another shot.

**Comment by forki** [comment]
Let me know. I can try to change permissions if needed

**Comment by eulerfx** [comment]
@forki: Maybe i was doing the wrong thing? What are the steps to publish a nuget package? I was doing `fake PublishNuget` and got the following output:

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                  Duration
------                  --------
Clean                   00:00:00.0142442
AssemblyInfo            00:00:00.0197850
Build                   00:00:02.8383899
RunTests                00:00:32.5588570
CleanDocs               00:00:00.0216259
GenerateHelp            00:00:07.1349638
GenerateReferenceDocs   00:00:06.9520890
GenerateDocs            00:00:00.0000832
All                     00:00:00.0000568
NuGet                   00:00:01.1754549
BuildPackage            00:00:00.0002258
PublishNuget            00:00:00.1366100
Total:                  00:00:50.9379089
Status:                 Ok
---------------------------------------------------------------------```

The version on nuget is still 2.0.3 though.

**Comment by forki** [comment]
IIRC we projectscaffolded the project.
Create a release.cmd as described in
http://fsprojects.github.io/ProjectScaffold/release-process.html

**Comment by eulerfx** [comment]
@forki Thanks, I just did that and it is now errors with the following:

```Running build failed.
Error:
System.Exception: fatal: tag '2.0.4' already exists
   at Fake.Git.CommandHelper.gitCommand(String repositoryDir, String command) in C:\code\fake\src\app\FakeLib\Git\CommandHelper.fs:line 62
   at Fake.Git.Branches.tag(String repositoryDir, String tag) in C:\code\fake\src\app\FakeLib\Git\Branches.fs:line 122
   at FSI_0001.Build.clo@281-48.Invoke(Unit _arg3)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 483
```

**Comment by eulerfx** [comment]
I think this may have been caused by a previous failure to release. I bumped it to v2.0.5 and it seemed to have succeeded. Waiting for nuget to update..

**Comment by eulerfx** [comment]
@forki: it looks like it didn't publish still. I see a release created back in January 13th (https://github.com/fsprojects/FSharp.Control.AsyncSeq/releases) for v2.0.5 which might have been me attempting to release this back then. But still nothing on nuget. I created the release.cmd file as described in the link you sent and ran it successfully. Should I try bumping the version to v2.0.6?

**Comment by forki** [comment]
looks like you didn't commit the version no. bump in the release notes!?
but you are right - it doesn't publish to nuget. Will investigate

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/14109525/be43cb42-f5c2-11e5-8d03-6e5915b667ff.png)

Ok found it. Now the fails for me. Which is correct since I don't have publish rights for this project on nuget. Please pull latest master and run your release.cmd

**Comment by eulerfx** [comment]
Alright I was able to release.cmd with v2.0.7. Let's see if this pushes it to nuget:

```---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                  Duration
------                  --------
Clean                   00:00:00.1001341
AssemblyInfo            00:00:00.0239822
Build                   00:00:02.7380658
RunTests                00:00:31.6542800
CleanDocs               00:00:00.0204461
GenerateHelp            00:00:06.9679867
GenerateReferenceDocs   00:00:06.9715628
GenerateDocs            00:00:00.0000942
All                     00:00:00.0000780
ReleaseDocs             00:00:04.3667420
NuGet                   00:00:01.0401061
BuildPackage            00:00:00.0000777
PublishNuget            00:00:00.1319058
Release                 00:00:07.8426080
Total:                  00:01:02.0879610
Status:                 Ok```

**Comment by forki** [comment]
Mhm doesn't look like it. It seems it doesn't create the packages. Do you see the package in the temp folder?

**Comment by eulerfx** [comment]
My mistake, I didn't actually merge after fetching upstream. v2.0.8 there now. Thanks a lot!

**Comment by forki** [comment]
Puhh. Cool. Case closed

**Comment by eulerfx** [comment]
@jlewicki give v2.0.8 a try now.

**Comment by jlewicki** [comment]
Success!  
Thank you gentlemen.
