### ISSUE TITLE
Memory leak in AsyncSeq.bufferByCountAndTime

### ISSUE THREAD

**Issue by endeavour** [fsprojects/FSharp.Control.AsyncSeq#52]
Leave this running for a few minutes and you'll get an OutOfMemoryException.

    open FSharp.Control

    [<EntryPoint>]
    let main argv = 

      let rec nums () =
        asyncSeq {
        yield Array.zeroCreate 100000
        yield! nums ()
        }

      let numbers = nums ()

      let buffered = numbers |> AsyncSeq.bufferByCountAndTime 1000 (int 10) |> AsyncSeq.toObservable

      buffered.Subscribe(fun _ -> System.GC.Collect()) |> ignore

      System.Console.ReadKey() |> ignore

      printfn "%A" argv
      0 // return an integer exit code

**Comment by eulerfx** [comment]
Hey, thanks for posting the issue. This is likely caused by a perf issue with the internal implementation of the append operation. I need to merge the perf fixes made in (https://github.com/eulerfx/FSharp.Control.AsyncSeq/tree/perf) to correct this.

**Comment by endeavour** [comment]
Ok thanks! Any update on when those changes will be merged?

**Comment by eulerfx** [comment]
I should just merge it, nearly as is. I got caught up in optimizing it even more, but its much better in than master anyway. I'll see if I can work on it over the next week.

**Comment by eulerfx** [comment]
I made a [PR](https://github.com/fsprojects/FSharp.Control.AsyncSeq/pull/53) in which I wasn't able to reproduce the issue, hopefully it solves it.

**Comment by eulerfx** [comment]
https://www.nuget.org/packages/FSharp.Control.AsyncSeq/2.0.9
