### ISSUE TITLE
Target .NET 4.5 to use ExceptionDispatchInfo

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Control.AsyncSeq#6]
This library catches exceptions in various places and turns them into data, which loses stack traces.  We should probably switch to .NET 4.5 to be able to use the ExceptionDispatchInfo type which preserves stack traces https://msdn.microsoft.com/en-us/library/system.runtime.exceptionservices.exceptiondispatchinfo(v=vs.110).aspx

**Comment by CarstenKoenig** [comment]
I can try this but probably there are quite some people out there that still are restricted to 4.0 because of older (server-)OS (?)

**Comment by dsyme** [comment]
I think we can safely assume .NET 4.5 for work going ahead. FSharp.Core 4.4.0.0 assumes .NET 4.5. 

Take a good look at https://visualfsharp.codeplex.com/SourceControl/network/forks/dsyme/cleanup/contribution/7550 if you want to give it a crack.

**Comment by dsyme** [comment]
Basically, whenever you treat exceptions as data, you should use ExceptionDispatchInfo instead, e.g. change
``
        type internal ObservableUpdate<'T> = 
            | Next of 'T
            | Error of exn
            | Completed
``
to
``
        type internal ObservableUpdate<'T> = 
            | Next of 'T
            | Error of ExceptionDispatchInfo
            | Completed
``
If you do that systematically and follow the techniques in the PR then you should get decent stack traces.

**Comment by fsprojectsgit** [comment]
Implemented via https://github.com/fsprojects/FSharp.Control.AsyncSeq/pull/27
