### ISSUE TITLE
Question on caching

### ISSUE THREAD

**Issue by quant1729** [fsprojects/FSharp.Control.AsyncSeq#60]
Hello, 

Thank you for such a great library. I have a question about sequence caching. I want to have one sequence generator function, that then mapped into two different data streams (independent), and then zipped at some point. I have the following sample code: 

`let oneTwo = asyncSeq { 
        do! Async.Sleep(1000)
        yield 1
        do! Async.Sleep(1000)
        yield 2 } 
    
    let cached = oneTwo |> AsyncSeq.cache

    let first = cached |> AsyncSeq.map (fun x -> -x)
    let second = cached |> AsyncSeq.map (fun x -> x * 4)

    let zipped = (first, second) ||> AsyncSeq.zip

    zipped 
    |> AsyncSeq.iter(fun (f,s) -> printf "--> First %A Second %A \r\n" f s) 
    |> Async.Start`

The output is the following: 

--> First -1 Second 4
--> First -2 Second 4

Seems like second sequence is not mapped correctly. Can you please clarify what would be the idiomatic way of doing this?

Thank you,
Pavel

**Comment by eulerfx** [comment]
Looks like a bug with AsyncSeq.cache. Thanks for reporting. This seems to be caused by how the internal counter is incremented. Also, another problem is that the cached sequence can't be iterated by to concurrent threads. Will update once fixed.

**Comment by quant1729** [comment]
Thank you. Caching is really cool feature of the library.

**Comment by eulerfx** [comment]
https://www.nuget.org/packages/FSharp.Control.AsyncSeq/2.0.11 should fix it

**Comment by quant1729** [comment]
Thank you. Will test it.
