### ISSUE TITLE
Simple aggregation

### ISSUE THREAD

**Issue by quant1729** [fsprojects/FSharp.Control.AsyncSeq#62]
Hello Lev, 

I was trying to perform some simple aggregation using AsyncSeq, and seems like I am facing an issue. My code first: 

`    let inputStream = asyncSeq { 
        do! Async.Sleep(1000)
        yield 1
        do! Async.Sleep(1000)
        yield 2
        do! Async.Sleep(1000)
        yield 3
        do! Async.Sleep(1000)
        yield 4
        do! Async.Sleep(1000)
        yield 5 
    } 

    let res = 
        inputStream
        |> AsyncSeq.groupBy(fun x -> x % 3)
        |> AsyncSeq.mapAsync( snd >> AsyncSeq.lastOrDefault 0)
    
    res
    |> AsyncSeq.iter(fun x -> printfn "--> %A" x) 
    |> Async.Start`

I am trying to group the data and aggregate it using the last value in each of the groups. e.g. daily close price from intraday bars. I am using lastOrDefault function for this. The code above doesn't produce the expected agg values, and I think there should be a simpler way to do this. Can you please advise?

Best regards,
Pavel

**Comment by eulerfx** [comment]
Try this:

```
let res = 
    inputStream
    |> AsyncSeq.groupBy(fun x -> x % 3)
    |> AsyncSeq.mapAsyncParallel ( snd >> AsyncSeq.lastOrDefault 0)
```

The sequence of sequences returned by `groupBy` must be iterated in parallel. If you iterate sequentially, the first sub-sequence will never complete because other haven't been consumed, and therefore the input sequence is still unconsumed, therefore we don't know whether more items can arrive into this sub-sequence.

**Comment by quant1729** [comment]
I see. Thank you for clarification. Interesting moment. 

Wanted to ask you what do you think would be the best way to model price series aggregation with 1 minute data aggregating into 1 day using your library? With updates every minute. Also having intermediate(unfinished) bars.  Couldn't find any similar ideas in the published examples,

**Comment by eulerfx** [comment]
Maybe you need a windowing function? I haven't put one into this library yet, but had a need in a projected dependent on this, so I added it on top. Take a look [here](https://github.com/jet/kafunk/blob/master/src/kafunk/Utility/AsyncSeq.fs#L118).
