### ISSUE TITLE
the `return` of `asyncSeq` builder is non intuitive

### ISSUE THREAD

**Issue by enricosada** [fsprojects/FSharp.Control.AsyncSeq#92]
The `return` of the `asyncSeq` computation ignore the value passed.
I found it bug prone when upgrading a library from asyncseq v1 to v2 types.

```fsharp
let a = asyncSeq {
    yield 1
    yield 2
    return 3
}
```

- no errors
- the `a` is `AsyncSeq<int>`
- as list, it's `[1; 2]` 
- the `3` is ignored, no warning, no errors

Same when trying to return another `asyncSeq` like

```fsharp
let b = asyncSeq {
   yield 4
   return a
}
```

i think that should be `return! a` to work correctly (not yet supported)

## workaround

always do `yield` and `yield!`

```fsharp
let a = asyncSeq {
    yield 1
    yield 2
    yield 3
}

let b = asyncSeq {
   yield 4
   yield! b
}
```

**Comment by eulerfx** [comment]
Related: https://github.com/fsprojects/FSharp.Control.AsyncSeq/issues/38

**Comment by enricosada** [comment]
@eulerfx I missed that. Closing this because is a duplicate.

Continuing discussion in other thread
