### ISSUE TITLE
Integrate with IAsyncEnumerable<'t>

### ISSUE THREAD

**Issue by baronfel** [fsprojects/FSharp.Control.AsyncSeq#96]
### Description

This library should offer integration points with [IAsyncEnumerable](https://msdn.microsoft.com/en-us/library/mt793980(v=vs.150).aspx?cs-save-lang=1&cs-lang=fsharp), to paper over the task->async translations in one place.

That might look like a binding API like `AsyncSeq.ofAsyncEnumerable`, `AsyncSeq.toAsyncEnumerable`, extra computation builder overloads for the type, etc.

**Comment by eulerfx** [comment]
Yes, I think this makes sense.
